language: cpp
compiler: gcc
dist: xenial

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'

install: 
  # C++17
  - sudo apt-cache search  llvm
  - sudo apt-get install -qq g++-8 cmake llvm
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

script:
  - llvm-config --cxxflags --ldflags --system-libs --libs engine interpreter
  - cmake dev/floyd_speak 
  - cmake --build . 
