language: cpp
compiler: gcc
dist: xenial

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
  - sudo apt-get update -qq


install: 
  # C++17
  - sudo apt-cache search  llvm-8
  - sudo apt-get install -qq --allow-unauthenticated  g++-8 cmake llvm-8-dev libedit-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - dpkg-query -L llvm-8
  #- sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-8 90



script:
  - llvm-config --cxxflags --ldflags --system-libs --libs engine interpreter
  - llvm-config-8 --cxxflags --ldflags --system-libs --libs engine interpreter
  - cmake dev/floyd 
  - cmake --build . 
