# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2

jobs:
  build:
    docker:
       - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake llvm'
      - run:
          name: Creating Build Files
          command: 'cmake /root/project/dev/floyd_speak/ -B build'
      - run:
           name: Creating Binary Files
           command: 'cmake --build build'
      - run:
           name: floyd Unit Testing
           command: './build/floydut runtests'