# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2

jobs:
  build:
    docker:
       - image: "archlinux/base"
    steps:
      - checkout
      - run:
          name: Installing dev env
          command: 'pacman -Sy --noconfirm && pacman -S --noconfirm git gcc make cmake llvm'
      - run:
          name: ls
          command: 'pwd && ls'
      - run:
          name: Creating Build Files
          command: 'cmake /root/project/dev/floyd_speak/'
      - run:
           name: Creating Binary Files
           command: 'make'
      - run:
           name: floyd Unit Testing
           command: './floydut runtests'

  build-mac:
    macos:
       xcode: "10.0.0"
    workDir: /Users/distiller/project/dev/ 
    steps:
      - checkout
      - run:
          name: ls
          command: 'pwd && ls'
      - run:
          name: Brew update
          command: 'brew update'
      - run:
          name: Brew upgrade
          command: 'brew upgrade'   
      - run:
          name: Brew install llvm
          command: 'brew install llvm@8.0.0'
      - run:
           name: Creating Application
           command: 'cd dev && xcodebuild'
      - run:
           name: floyd Unit Testing
           command: 'build/Release/floydut runtests'
      - run:
          name: Compress app  and result for storage
          command: zip -r floyd.zip build/Release/floyd.app
      - store_artifacts:
          path: floyd.zip
          destination: floyd
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - build-mac    
