name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: add-apt-gcc8
      run:  sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - name: apt-get
      run: |
        sudo apt-get install -qq --allow-unauthenticated  g++-8 cmake llvm-8-dev libedit-dev
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
        dpkg-query -L llvm-8
    - name: install-llvm
      run: |
        sudo add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
        sudo apt-get install -qq --allow-unauthenticated cmake llvm-8-dev libedit-dev
    - name: configure
      run: |
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
        cmake compiler
    - name: make
      run: cmake --build . 
    
  build-mac-cmake:

    runs-on: macos-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Brew install
      run: |
        brew install llvm@8
        brew install cmake
        brew info llvm
    - name: configure 
      run: cmake compiler
    - name: make
      run: cmake --build . 

  build-mac-xcode:
    runs-on: macos-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Brew install
      run: |
        brew install llvm@8
        brew install cmake
    - name: Creating Application
        run: 'xcodebuild -scheme distributable build'
    - name: floyd Hwcaps
        run: 'ls /Users/distiller/Library/Developer/Xcode/DerivedData &&  cd  /Users/distiller/Library/Developer/Xcode/DerivedData/floyd-*/Build/Products/Release;./floyd hwcaps'

