name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
     matrix:
      platform: [ubuntu-latest, macos-latest]

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: add-apt-gcc8
      run:  sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - name: apt-get
      run: |
      sudo apt-get install -qq --allow-unauthenticated  g++-8 cmake llvm-8-dev libedit-dev
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
      dpkg-query -L llvm-8
    - name: install-llvm
      run: |
      sudo add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
      sudo apt-get install -qq --allow-unauthenticated cmake llvm-8-dev libedit-dev
    - name: configure
      run: cmake compiler
    - name: make
      run: cmake --build . 
    

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Brew install
      run: |
      brew install llvm@8
      brew install cmake
    - name: configure
      run: cmake compiler
    - name: make
      run: cmake --build . 
